### ISSUE TITLE
Add a "back to top" arrow on post pages

### ISSUE THREAD

**Issue by ScreamingHawk** [Ao-Collaboration/Ao-Collaboration.github.io#11]
Add a button that appears floating on bottom right. Clicking the button scrolls the user back to the top of the page. This should only appear on the posts page

**Comment by ScreamingHawk** [comment]
Example page https://www.terremotocentroitalia.info/post/ (scroll down)

**Comment by ScreamingHawk** [comment]
@MoyaSparklefarts I've added smooth scrolling to get the nice flow back to the top. It affects user scrolling too. 

If you don't like it, it can removed by deleting these lines: 
https://github.com/Ao-Collaboration/Ao-Collaboration.github.io/blob/217abf81f123a0706900cbb038d726dc44760413/assets/css/main.css#L19-L25

**Comment by ScreamingHawk** [comment]
No complaints, it must be good. :) Closing

**Comment by MoyaSparklefarts** [comment]
Whoops I didn't see this issue!
Can we remove the black border on the button?

**Comment by ScreamingHawk** [comment]
Can do. Could you reopen it so I don't forget please.

**Comment by ScreamingHawk** [comment]
I don't see a black border

![image](https://user-images.githubusercontent.com/1460552/102827569-a82fbe00-4447-11eb-8ae7-14e8f62459ec.png)

Can you replicate this? What browser are you using

**Comment by MoyaSparklefarts** [comment]
This is with Chrome
![image](https://user-images.githubusercontent.com/73916478/102835538-dd460b80-445b-11eb-8bc5-68fcbe114d4a.png)

**Comment by MoyaSparklefarts** [comment]
This is with Edge Chromium
![image](https://user-images.githubusercontent.com/73916478/102835578-fb137080-445b-11eb-8e22-e52454b66ac9.png)

**Comment by ScreamingHawk** [comment]
The black border is how your browser renders that emoji. I'll change it to text and arrow so it's more consistent with the rest of the site and cross browser

**Comment by ScreamingHawk** [comment]
Updated @MoyaSparklefarts . How's that?

**Comment by MoyaSparklefarts** [comment]
Looks good now! We can close this issue I think?

**Comment by ScreamingHawk** [comment]
Sounds good :)
