### ISSUE TITLE
Add profile cards in the team.md page

### ISSUE THREAD

**Issue by MoyaSparklefarts** [Ao-Collaboration/Ao-Collaboration.github.io#12]
Hey @ScreamingHawk 

I don't want to break things by adding random CSS where I shouldn't. I wanted to have proper profile cards on the website.
Nothing crazy, the basic one from the w3schools website is good: https://www.w3schools.com/howto/howto_css_cards.asp
And then make it a flip card for the blurb: https://www.w3schools.com/howto/howto_css_flip_card.asp

These are the profile pictures but let me know if I need to make them square and re-upload them
assets/img/Kate-website.png
assets/img/Serena-website.png

Possible? If so, ETA?

**Comment by ScreamingHawk** [comment]
Maybe today if I get a chance. Shouldn't be too difficult. 

Could you post the text you want and I can test that works too?

**Comment by MoyaSparklefarts** [comment]
Kate Standen
Founder and Salesforce Consultant
@misskatles will have to give you her blurb 😺 

Serena Cappellini
Salesforce Specialist
Serena comes from 15+ years of customer experience across many different sectors, including SaaS and web agencies. Here at Ao Collaboration, she is invested in helping improving processes and operation, as well as offering client solution to their specific needs. When not at work, Serena can be found initiating novices to the fine art of playing Dungeons and Dragons, cooking food and pairing it with tine, and lecturing people on what ingredients do and do not go on pizza.

**Comment by ScreamingHawk** [comment]
Done the cards. Having trouble with the flipping because the blurb content side is bigger than the image side. Will look at this again later. 

Worth considering a non flipping design too, as mobile doesn't have hover effects.

**Comment by MoyaSparklefarts** [comment]
Moved it here https://aocollab.tech/team/

What should we do instead of flipping design? (it sounds like we are trying not to swear)
Hover over? Click to expand?

Also, how painful would it be to add the following icons:
- email
- linkedin

**Comment by ScreamingHawk** [comment]
Something like this? 
![image](https://user-images.githubusercontent.com/1460552/101289795-82a98e80-3863-11eb-90e8-241f17cd2818.png)

Any kind of hover effect for more info will be undiscovered on mobile. Click is best for usability.

**Comment by ScreamingHawk** [comment]
I'm not convinced the card is good for long format text 
![image](https://user-images.githubusercontent.com/1460552/101289962-61956d80-3864-11eb-860c-28424168fe57.png)

What about the contact card and then the blurb below? Or a pop out with more info like https://www.atlassian.com/company/people ?

**Comment by MoyaSparklefarts** [comment]
Pop out like on the Atlassian page wins - I like the clean look of the cards but you're right, too much text makes it hideous!

**Comment by ScreamingHawk** [comment]
Added the contact card modals @MoyaSparklefarts . Kate still needs a blurb

**Comment by MoyaSparklefarts** [comment]
'Kate is an enigma' XD
Looking good!
