### ISSUE TITLE
Title hard to read with image background

### ISSUE THREAD

**Issue by ScreamingHawk** [Ao-Collaboration/Ao-Collaboration.github.io#16]
https://aocollab.tech/2020-11-28-what-is-crm-why-salesforce/

![image](https://user-images.githubusercontent.com/1460552/102031459-f2e38180-3e1a-11eb-912c-e76edaad29db.png)

@MoyaSparklefarts Think we need a different image here

**Comment by MoyaSparklefarts** [comment]
Ah yes I'll fix the image, I put a dark overlay when we had the white title - thanks!
