### ISSUE TITLE
Add web to case email field

### ISSUE THREAD

**Issue by ScreamingHawk** [Ao-Collaboration/Ao-Collaboration.github.io#18]
Add a Salesforce web to case email section. 

- [x] Create web to case includes HTML
- [x] Add Google Captcha key to SF
- [x] Style the web to case form
- [x] Add the form to [page]

**Comment by MoyaSparklefarts** [comment]
@ScreamingHawk I had to generate another HTML code with the most recent keys provided - I didn't update in here: https://github.com/Ao-Collaboration/Ao-Collaboration.github.io/blob/master/_includes/web-to-case-form.html as I suspect I'd just flush all the styling down the toilet.

EDIT: I sent you the code in Slack

**Comment by ScreamingHawk** [comment]
Form updated :) @MoyaSparklefarts 

We need a page for "thanks for your email" and the redirect link needs to be updated in the form

**Comment by MoyaSparklefarts** [comment]
Do you reckon we're ready to add the form here: https://aocollab.tech/contact/ ?
Instead of the 'contact email' part.

**Comment by ScreamingHawk** [comment]
Deployed. Happy to close this ticket :tada:
