### ISSUE TITLE
Contact form on small business solutions page

### ISSUE THREAD

**Issue by ScreamingHawk** [Ao-Collaboration/Ao-Collaboration.github.io#21]
![image](https://user-images.githubusercontent.com/1460552/107569407-24c36980-6c4d-11eb-8703-2db91e48a355.png)

There is an email link on the small business solutions page. Should this use the contact form instead?

**Comment by MoyaSparklefarts** [comment]
@ScreamingHawk definitely, thanks for noticing it!

**Comment by MoyaSparklefarts** [comment]
Done

**Comment by MoyaSparklefarts** [comment]
No @ScreamingHawk hang on - I just copied

`Please use the form below

{% include web-to-case-form.html %}`

But it looks like the styling isn't there?


![image](https://user-images.githubusercontent.com/73916478/107570521-83d5ae00-6c4e-11eb-97b0-acdcbec2f027.png)

**Comment by ScreamingHawk** [comment]
I've updated the style sheet so it will work site wide now @MoyaSparklefarts
