### ISSUE TITLE
Add posts page

### ISSUE THREAD

**Issue by ScreamingHawk** [Ao-Collaboration/Ao-Collaboration.github.io#4]
Add a page that contains all the posts. Should still have a couple posts on the main page

**Comment by MoyaSparklefarts** [comment]
How taxing would it be to add a tag filter to search through all the articles?

**Comment by ScreamingHawk** [comment]
Not too hard. There is some built in support for it. Would only have to style the page

**Comment by MoyaSparklefarts** [comment]
Sweet! Let me know when you have time to create it :-)

**Comment by ScreamingHawk** [comment]
Doubled checked. We get it for free when a page is created. 
![image](https://user-images.githubusercontent.com/1460552/99611519-b4a3ae00-2a78-11eb-8186-783f4a5c93e3.png)

Make sure you have `tags` in the post front matter
![image](https://user-images.githubusercontent.com/1460552/99611611-e288f280-2a78-11eb-8538-a5d2b533ec7f.png)

**Comment by ScreamingHawk** [comment]
Have 'Resources' in the navbar and 'posts' and 'tags' as children
