### ISSUE TITLE
add subscribe email functionality to website for the Mailchimp stuff

### ISSUE THREAD

**Issue by misskatles** [Ao-Collaboration/Ao-Collaboration.github.io#6]
@MoyaSparklefarts  Please assist @ScreamingHawk .

**Comment by MoyaSparklefarts** [comment]
`
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://tech.us2.list-manage.com/subscribe/post?u=b90bcfc66fe56e8f53d017973&amp;id=265e339d68" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Subscribe</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-FNAME">First Name  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Last Name  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="LNAME" class="required" id="mce-LNAME">
</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_b90bcfc66fe56e8f53d017973_265e339d68" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

`

**Comment by MoyaSparklefarts** [comment]
[subscribe-code.txt](https://github.com/Ao-Collaboration/Ao-Collaboration.github.io/files/5522965/subscribe-code.txt)

**Comment by ScreamingHawk** [comment]
Thanks. Ezpz to add. On which page?

**Comment by MoyaSparklefarts** [comment]
Probably the contact page for now, definitely the blog page once it's up.

**Comment by ScreamingHawk** [comment]
Added. Worth testing out. The test on the page you get directed too will be editable on MailChimp. There's different text if you forget to fill a field. 

Please close the ticket if you're happy with it

**Comment by MoyaSparklefarts** [comment]
It works fine, closing now 👍
