### ISSUE TITLE
Add a footer menu with the items we do not want in the main navbar

### ISSUE THREAD

**Issue by MoyaSparklefarts** [Ao-Collaboration/Ao-Collaboration.github.io#7]
- Meet the Team
- Terms of Service (page ready)
- Privacy Policy
- I can't think of anything else right now

**Comment by ScreamingHawk** [comment]
Added footer links. Configurable via `_config.yaml > footer-links` in the same way `navbar-links` work

![image](https://user-images.githubusercontent.com/1460552/99716561-24637880-2b0d-11eb-80aa-eb9c6610938c.png)

**Comment by ScreamingHawk** [comment]
![image](https://user-images.githubusercontent.com/1460552/99717284-19f5ae80-2b0e-11eb-9999-5465cae561de.png)

**Comment by MoyaSparklefarts** [comment]
Created Privacy Policy page and added it to footer menu.
I'll close this - thanks @ScreamingHawk !
