### ISSUE TITLE
help.aocollab.tech subdomain as our Knowledge Base website

### ISSUE THREAD

**Issue by MoyaSparklefarts** [Ao-Collaboration/Ao-Collaboration.github.io#9]
- separate website from the main aocollab.tech
- subdomain help.aocollab.tech
- website structure like this:
  - http://jekyllthemes.org/themes/wiki-blog/ (it's a bit ugly though)
  - http://jekyllthemes.org/themes/jekyll-help-center-theme/ (this is very pretty but unsure how it would look like with many articles)
  - http://jekyllthemes.org/themes/edition/
- ability to lock content behind login page? Not sure if achievable

Your thoughts @ScreamingHawk ? If you have any other better templates in mind by all means! Those are just some I found with some quick research to give an idea of what I'm visualizing.

**Comment by ScreamingHawk** [comment]
Yes we can!

For dev reference: [How to add subdomain][1]

> ability to lock content behind login page? Not sure if achievable

The jekyll wiki uses github as it's content editing. If anyone wanted to edit a page they would log into github and do the same thing you are doing. But it would need to be approved by someone from our team before the change is merged in and made live. 

---

How much of the content on the wiki will be applicable to multiple clients? The way I understand the SF implementations is that they are very custom. Wiki results would be for particular clients. Not sure how much general wiki information there will be. 

I wonder if something like [Notion][0] would be a better fit for this. 

Jekyll is designed as a blogging platform, while tags are good for filtering content it doesn't give you much in the way of a folder structuring when you have related content. 

[0]: https://www.notion.so/customers/personal-websites
[1]: https://webapps.stackexchange.com/questions/42455/publishing-more-than-one-site-on-github-pages

**Comment by MoyaSparklefarts** [comment]
Ah yes, I used Nuclino a for a start up project that required lots of document sharing but needed different access for different areas (D&D platform for both dungeon masters and players :P ) - Notion seems to be a better version of that, at a reasonably good price.

All the other KB specific platforms (HelpDocs, BetterDocs, ArchBee, etc) come at a price and at that point we're better to move to the Service Cloud in SalesForce @misskatles ?

**Comment by misskatles** [comment]
Notion seems like it will do what we need it to do for now.

@MoyaSparklefarts do you want to go ahead with the trial and see if it suits?  Given that you're more familiar with what we need at a minimum.

**Comment by MoyaSparklefarts** [comment]
Yep happy to 👍

**Comment by MoyaSparklefarts** [comment]
Done www.notion.so/aocollab

@misskatles I started to give it a bit of structure:
- Internal Processes
- Client KB To-Do list

Closing this 👍
